version: 2.1

jobs:
  build-and-test:
    docker: # run the steps with Docker
      - image: circleci/python:3.7.6
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest
          name: Test
      - run:
          command: pycodestyle --ignore=W291,W293,W503 --exclude=*build,.ipynb* tests/common/test_stats.py  
          name: Pep8

workflows:
  main:
    jobs:
      - build-and-test
